version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_mng
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
    environment:
      #MONGO_INITDB_ROOT_USERNAME: vladm
      #MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongodb_def

volumes:
  mongo-data: